name: python-project
dependencies:
  - python=3.9
  - rich
  - python-dotenv
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pygam
  - sshtunnel
  - sqlalchemy
  - requests
  - mysql-connector-python
  - scipy
  - tornado
  - statsmodels